name: Build App on Pull Request
on:
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run workflow on"
        required: true
        default: "main"

jobs:
  build_app:
    runs-on: ubuntu-latest
    environment: development
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.1
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - name: PNPM install
        run: pnpm i
      - name: Build App
        env:
          ZE_SECRET_TOKEN: ${{ secrets.ZE_SECRET_TOKEN }}
          ZE_API: ${{ vars.ZE_API }}
          ZE_API_GATE: ${{ vars.ZE_API_GATE }}
        run: |
          cd zephyr-examples/create-mf-app-rspack
          pnpm i
          DEBUG=* pnpm run build
      - name: Zephyr deploy summary
        uses: ./ # Uses an action in the root directory
        id: zephyr-summary
        with:
          application_uid: create-mf-app-rspack-host.deploy-summary-action.zephyrcloudio
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print zephyr deploy summary
        run: echo "Deployed to ${{ steps.zephyr-summary.outputs.version_url }}"
